// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAUoUXKMeKGH8OZmhZu5WFSOS3ocDnKSk',
    appId: '1:732713564724:web:46263f83100faf5359e861',
    messagingSenderId: '732713564724',
    projectId: 'fir-bfc34',
    authDomain: 'fir-bfc34.firebaseapp.com',
    databaseURL: 'https://fir-bfc34-default-rtdb.firebaseio.com',
    storageBucket: 'fir-bfc34.appspot.com',
    measurementId: 'G-WZ85YJ2RWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM0w343gGPm7U7bkggRnmXZSlBkaqTjhI',
    appId: '1:732713564724:android:6af82e79d50bbdc559e861',
    messagingSenderId: '732713564724',
    projectId: 'fir-bfc34',
    databaseURL: 'https://fir-bfc34-default-rtdb.firebaseio.com',
    storageBucket: 'fir-bfc34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYZ5BPZXS3_ksBWtB0C61PPJdR8t0KP2g',
    appId: '1:732713564724:ios:9b39b54f38195d1859e861',
    messagingSenderId: '732713564724',
    projectId: 'fir-bfc34',
    databaseURL: 'https://fir-bfc34-default-rtdb.firebaseio.com',
    storageBucket: 'fir-bfc34.appspot.com',
    iosClientId: '732713564724-n41edattl0gfq3fep81mf6pao55hfq9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.newyou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYZ5BPZXS3_ksBWtB0C61PPJdR8t0KP2g',
    appId: '1:732713564724:ios:9b39b54f38195d1859e861',
    messagingSenderId: '732713564724',
    projectId: 'fir-bfc34',
    databaseURL: 'https://fir-bfc34-default-rtdb.firebaseio.com',
    storageBucket: 'fir-bfc34.appspot.com',
    iosClientId: '732713564724-n41edattl0gfq3fep81mf6pao55hfq9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.newyou',
  );
}
